<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-27 at 17:56:43.
 */
class DefaultPageControllerTest extends PHPUnit_Framework_TestCase
{


	/**
	 * @var DefaultPageController
	 */
	protected $object;
	private $referenceFile = __DIR__ . "/defaultpagecontrollerTestOutputReference.txt";


	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp () {
		$model = new DefaultPageModel();
		$view = new DefaultPageView();
		$model->subscribe ($view);

		$this->object = new DefaultPageController ($model, $view);
	}


	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown () {
		
	}


	/**
	 * @covers DefaultPageController::run
	 * @todo   create a mock model and view and make the defaultmodelandviewinto a base class.
	 */
	public function testRun () {
		$stream = fopen ("php://memory", "w+");

		$this->object->run ($stream);

		rewind ($stream);
		$this->assertStringEqualsFile ($this->referenceFile, stream_get_contents ($stream));
		fclose ($stream);
		$this->markTestIncomplete ("something needs to change, read comments");
	}


}
