<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-27 at 17:56:43.
 */
class DefaultPageControllerTest extends PHPUnit_Framework_TestCase {

        /**
         * @var DefaultPageController
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp() {
                $this->object = new DefaultPageController;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown() {
                
        }

        /**
         * @covers DefaultPageController::run
         * @todo   Implement testRun().
         */
        public function testRun() {
                // Remove the following lines when you implement this test.
                $this->markTestIncomplete(
                        'This test has not been implemented yet.'
                );
        }

}
