<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-27 at 17:56:56.
 */
class AccessControlServerTest extends PHPUnit_Framework_TestCase
{


	/**
	 * @var AccessControlServer
	 */
	protected $object;
	protected $adminMock;
	protected $routeMock;


	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp () {
		$this->object = new AccessControlServer;
		$this->adminMock = $this->getMockBuilder (Admin::class)
				->disableOriginalConstructor()
				->getMock();
		$this->routeMock = $this->getMockBuilder (Route::class)
				->disableOriginalConstructor()
				->getMock();
	}


	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown () {
		
	}


	/**
	 * @covers AccessControlServer::hasAccess
	 * @todo   Implement testHasAccess().
	 */
	public function testHasAccess () {

		$this->object->hasAccess($this->adminMock, $this->routeMock);
	}


}
