<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-27 at 17:56:56.
 */
class AccessControlServerTest extends PHPUnit_Framework_TestCase {

        /**
         * @var AccessControlServer
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp() {
                $this->object = new AccessControlServer;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown() {
                
        }

        /**
         * @covers AccessControlServer::hasAccess
         * @todo   Implement testHasAccess().
         */
        public function testHasAccess() {
                // Remove the following lines when you implement this test.
                $this->markTestIncomplete(
                        'This test has not been implemented yet.'
                );
        }

}
