<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-28 at 11:18:14.
 */
class DispatcherTest extends PHPUnit_Framework_TestCase
{


	/**
	 * @var Dispatcher
	 */
	protected $object;


	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp () {
		$this->object = new Dispatcher;
	}


	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown () {
		
	}


	/**
	 * @covers Dispatcher::run
	 * @todo   Implement testRun().
	 */
	public function testRun () {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}


}
