<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-29 at 23:16:42.
 */
class SessionTest extends PHPUnit_Framework_TestCase
{


	/**
	 * @var Session
	 */
	protected $object;


	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp () {
		$this->object = new Session;
	}


	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown () {
		
	}


	/**
	 * @covers Session::start
	 * @todo   Implement testStart().
	 */
	public function testStart () {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}


	/**
	 * @covers Session::get
	 * @todo   Implement testGet().
	 */
	public function testGet () {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}


	/**
	 * @covers Session::set
	 * @todo   Implement testSet().
	 */
	public function testSet () {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}


	/**
	 * @covers Session::getAllData
	 * @todo   Implement testGetAllData().
	 */
	public function testGetAllData () {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}


	/**
	 * @covers Session::__destruct
	 * @todo   Implement test__destruct().
	 */
	public function test__destruct () {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}


}
