<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-27 at 17:57:37.
 */
class SessionTest extends PHPUnit_Framework_TestCase {

        /**
         * @var Session
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp() {
                $this->object = new Session;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown() {
                
        }

        /**
         * @covers Session::get
         * @todo   Implement testGet().
         */
        public function testGet() {
                // Remove the following lines when you implement this test.
                $this->markTestIncomplete(
                        'This test has not been implemented yet.'
                );
        }

        /**
         * @covers Session::getData
         * @todo   Implement testGetData().
         */
        public function testGetData() {
                // Remove the following lines when you implement this test.
                $this->markTestIncomplete(
                        'This test has not been implemented yet.'
                );
        }

}
