-- MySQL Script generated by MySQL Workbench
-- Sat 06 May 2017 03:40:07 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
use go_testdb;

drop table if exists `go_testdb`.`pepper`;
drop table if exists `go_testdb`.`gouser`;
drop table if exists `go_testdb`.`resource`;
drop table if exists `go_testdb`.`accessrule`;

create table `go_testdb`.`pepper` (
	`pepperstring` varchar(100))
engine = MEMORY;
insert into `go_testdb`.`pepper` value("FKrDfv0w3B");
-- -----------------------------------------------------
-- Table `go_testdb`.`gouser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `go_testdb`.`gouser` (
  `id` INT NOT NULL ,
  `email` VARCHAR(100) NULL,
  `salt` CHAR(20) NULL COMMENT '\n			',
  `hash` VARCHAR(512) NULL,
  `usertype` VARCHAR(45) NULL,
  `nick` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = MEMORY;


-- -----------------------------------------------------
-- Table `go_testdb`.`resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `go_testdb`.`resource` (
  `id` INT NOT NULL,
  `uri` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`))
ENGINE = MEMORY;


-- -----------------------------------------------------
-- Table `go_testdb`.`accessrule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `go_testdb`.`accessrule` (
  `id` INT NOT NULL,
  `gouser_id` INT NULL,
  `resource_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_accessrule_1_idx` (`gouser_id` ASC),
  INDEX `fk_accessrule_2_idx` (`resource_id` ASC),
  CONSTRAINT `fk_accessrule_1`
    FOREIGN KEY (`gouser_id`)
    REFERENCES `go_testdb`.`gouser` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accessrule_2`
    FOREIGN KEY (`resource_id`)
    REFERENCES `go_testdb`.`resource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = memory;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
