<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-27 at 17:58:10.
 */
class DefaultPageViewTest extends PHPUnit_Framework_TestCase {

        /**
         * @var DefaultPageView
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp() {
                $this->object = new DefaultPageView;
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown() {
                
        }

        /**
         * @covers DefaultPageView::getUpdate
         * @todo   Implement testGetUpdate().
         */
        public function testGetUpdate() {
                // Remove the following lines when you implement this test.
                $this->markTestIncomplete(
                        'This test has not been implemented yet.'
                );
        }

        /**
         * @covers DefaultPageView::processModelEvent
         * @todo   Implement testProcessModelEvent().
         */
        public function testProcessModelEvent() {
                // Remove the following lines when you implement this test.
                $this->markTestIncomplete(
                        'This test has not been implemented yet.'
                );
        }

}
