<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-27 at 17:55:53.
 */
class DefaultPageModelTest extends PHPUnit_Framework_TestCase
{


	/**
	 * @var DefaultPageModel
	 */
	protected $object;


	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp () {
		$this->object = new DefaultPageModel;
	}


	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown () {
		
	}


	/**
	 * @covers DefaultPageModel::doSomething
	 * @todo   Implement testDoSomething().
	 */
	public function testDoSomething () {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}


	/**
	 * @covers DefaultPageModel::subscribe
	 * @todo   Implement testSubscribe().
	 */
	public function testSubscribe () {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete (
			'This test has not been implemented yet.'
		);
	}


}
